### PR TITLE
refactor: publish multiple snapshots

### PR DESCRIPTION
**Pull request by InoMurko**
This PR will help bumping contracts:
1. it auto publishes comments when a particular snapshot is done (like below)
2. it creates two snapshots (MIN_EXIT_PERIOD 20s and 120s)
3. when you merge to master, the build will create a release and that will be published to the releases page
4. if you want to bump contract, all you need to do is to update SHA in `tester/CONTRACT_SHA` file

### CODE REVIEW

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: << parameters.min_exit_period >>.

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: << parameters.min_exit_period >>.

**Comment by InoMurko** [comment]
{data: Contracts snapshotted with MIN_EXIT_PERIOD: 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-8534341-MIN_EXIT_PERIOD-20.tar.gz., contracts: {
  authority_address: 0xc0f780dfc35075979b0def588d999225b7ecc56f,
  eth_vault: 0x0433420dee34412b5bf1e29fbf988ad037cc5db7,
  erc20_vault: 0x04badc20426bc146453c5b879417b25029fa6c73,
  payment_exit_game: 0x92ce4d7773c57d96210c46a07b89acf725057f21,
  plasma_framework_tx_hash: 0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c,
  plasma_framework: 0xc673e4ffcb8464faff908a6804fe0e635af0ea2f
}}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-4b5cc01-MIN_EXIT_PERIOD-20.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-20.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 120. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-120.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xe00074ee3160cec121bafadc20e741c1ebf34830fb67b2b6487b0b5574d2c39e",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-20.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 120. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-120.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xe00074ee3160cec121bafadc20e741c1ebf34830fb67b2b6487b0b5574d2c39e",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-20.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD: 120. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-cb5b3f1-MIN_EXIT_PERIOD-120.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xe00074ee3160cec121bafadc20e741c1ebf34830fb67b2b6487b0b5574d2c39e",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Review by achiurizo — DISMISSED** [review]
auto comments with contract snapshot information. WOW

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( a7e850342028c2115c27a8f51b846ace194c5822 ): 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-e837913-MIN_EXIT_PERIOD-20-PLASMA_CONTRACTS_SHA-a7e850342028c2115c27a8f51b846ace194c5822.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( a7e850342028c2115c27a8f51b846ace194c5822 ): 120. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-e837913-MIN_EXIT_PERIOD-120-PLASMA_CONTRACTS_SHA-a7e850342028c2115c27a8f51b846ace194c5822.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xe00074ee3160cec121bafadc20e741c1ebf34830fb67b2b6487b0b5574d2c39e",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Setting the SHA from master

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( c05b445bf704f00b2bd2f2bc563df0880cd54091 ): 20. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-f68364a-MIN_EXIT_PERIOD-20-PLASMA_CONTRACTS_SHA-c05b445bf704f00b2bd2f2bc563df0880cd54091.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xcd96b40b8324a4e10b421d6dd9796d200c64f7af6799f85262fa8951aed2f10c",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by InoMurko** [comment]
Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( c05b445bf704f00b2bd2f2bc563df0880cd54091 ): 120. Snapshot located at: https://storage.googleapis.com/circleci-docker-artifacts/data-elixir-omg-tester-plasma-deployer-dev-f68364a-MIN_EXIT_PERIOD-120-PLASMA_CONTRACTS_SHA-c05b445bf704f00b2bd2f2bc563df0880cd54091.tar.gz. Contract addresses: {
  "authority_address": "0xc0f780dfc35075979b0def588d999225b7ecc56f",
  "eth_vault": "0x0433420dee34412b5bf1e29fbf988ad037cc5db7",
  "erc20_vault": "0x04badc20426bc146453c5b879417b25029fa6c73",
  "payment_exit_game": "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  "plasma_framework_tx_hash": "0xe00074ee3160cec121bafadc20e741c1ebf34830fb67b2b6487b0b5574d2c39e",
  "plasma_framework": "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f"
}

**Comment by unnawut** [comment]
Can we move to @omisego-bot ? Seeing "InoMurko as a Bot" is scary 😱

**Comment by InoMurko** [comment]
Sure, as long as you give me the auth token @unnawut !

**Comment by unnawut** [comment]
👍Replaced `GITHUB_TOKEN` with @omisego-bot one now.

**Review by unnawut — APPROVED** [review]
why not

**Comment by pdobacz** [comment]
I'm not entirely sure what to put there, but maybe someone will know how to update https://github.com/omisego/devops/wiki/Upgrading-elixir-omg-to-a-new-plasma-contracts-SHA. Are the comments with the url/hashes going to appear in PRs to this repo, everytime a CI build concludes?

**Comment by InoMurko** [comment]
“ Are the comments with the url/hashes going to appear in PRs to this repo, everytime a CI build concludes?”
Yes, the comments will appear, and a merge to master will produce a release entry similar to: https://github.com/omisego-images/docker-elixir-omg/releases/tag/v1.0.0

**Pull request merged**
