### PR TITLE
feat: support plasma-contract-private

### PR DESCRIPTION
**Pull request by boolafish**
### Note
ref: https://github.com/omisego/velocity/issues/24
Due to [business confidential requirement of velocity](https://github.com/omisego/velocity/issues/15#issuecomment-608249579), we are starting to develop the new feature in private repo. However, as we need to be able to test ourselves in elixir-omg and other client lib (eg. omg-js) too, we would need this docker to support snapshot private repo sha as well.

- [x] Pass in GITHUB_TOKEN as docker args to get private repo access
- [x] Variable control on the repo to pull (`plasma-contracts` or `plasma-contracts-private`)
- [x] Update README on how to change the repo name

Side note: I read an article mentioning it is better to `git pull` instead of `git clone` to secure the token: https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/

> Note: Tokens should be treated as passwords. Putting the token in the clone URL will result in Git writing it to the .git/config file in plain text. Unfortunately, this happens for HTTP passwords, too. We decided to use the token as the HTTP username to avoid colliding with credential helpers available for OS X, Windows, and Linux.
To avoid writing tokens to disk, don’t clone. Instead, just use the full git URL in your push/pull operations:

### Test
Circle CI on both private and public would run:
- private repo test: [CI build](https://app.circleci.com/pipelines/github/omisego-images/docker-elixir-omg/209/workflows/4e055c54-9f88-46ad-991d-4b019f916664), [commit](https://github.com/omisego-images/docker-elixir-omg/pull/41/commits/7321a8580b303fb44824073ae13ab23489e1287d)
- public repo test: [CI build](https://app.circleci.com/pipelines/github/omisego-images/docker-elixir-omg/210/workflows/80c27fce-6023-4184-83fe-ab66f2f17139), [commit](https://github.com/omisego-images/docker-elixir-omg/pull/41/commits/a6cf91a40ff4d32dc74229abc7537713f526b8ae)

### CODE REVIEW

**Comment by unnawut** [comment]
Sooo, my understanding of what's left for this PR:

- Merge this PR to `master` so we have this repo-switching feature
- Add a new long-lasting branch `master-private` so that we can set `tester/CONTRACT_REPO_NAME` to `plasma-contracts-private` without impacting `master`
- To build new docker images for private contracts, we'll submit PRs to `master-private`. We don't really need `stable-` tag so we can just use the `dev-` images that are pasted in the PR.

Something like this?

**Comment by boolafish** [comment]
yes, all above is aligned with my thinking.

>  We don't really need stable- tag so we can just use the dev- images that are pasted in the P

agree. I am not sure do we not need some tag forever but starting with dev until it does not work seems like the path I would prefer to go with too.

**Comment by boolafish** [comment]
rebased. can @unnawut or @InoMurko help review? 🙏

**Review by unnawut — APPROVED** [review]
Let's get another ✅ though

**Review by InoMurko — APPROVED** [review]
LGTM!

**Comment by boolafish** [comment]
🙏 thanks for approval! It would also be nice if you can help press the merge button as I don't have the permission to do so 😅

**Pull request merged**
